condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 5
fn_single_line = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
# reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
reorder_imports = true
struct_field_align_threshold = 4
use_field_init_shorthand = true
imports_layout = "HorizontalVertical"
inline_attribute_width = 50
imports_granularity = "Module"
normalize_comments = true
