[package]
name = "egui-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-traits = { version = "0.4.0", optional = true }
eframe = "0.27.2"
egui = "0.27.2"
